import Head from "next/head";
import Hero from "../components/Hero";
import Events from "../components/Events";
import Counter from "../components/Counter.jsx";
import Timer from "../components/Timer";


export default function Home() {
  return (
    <div>
      <Head>
        <title>KIITFEST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo/kiitfest-logo.png" />
      </Head>
      <Hero/>
      <Events/>
      <Counter/>
     
    </div>
  );
}
